#!/usr/bin/env bash
# configures a server to listening on port 80 of all server’s active IPv4 IPs

Rm /etc/nginx/sites-enabled/default
Ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
Service nginx restar
