#!/usr/bin/env bash
# configures a server to listening on port 80 of all server’s active IPv4 IPs
Sudo sed -I “s/8080/80/” /etc/nginx/sites-enabled/default
Sudo service nginx restart
Echo “” | sudo dd status=none of=/run/nginx.pid
